# -*- coding: utf-8 -*-
"""Turkish_Legal_SML_Summarization_FineTuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHiRD5KyEXtSHGAs4nB21RS-anwQlVQu

# Dr. Öğr. Üyesi Ali Çetinkaya - Büyük Dil Modelleri (LLM) Dersi Final Projesi
**Proje Adı:** Türkçe Hukuki Metinlerin Küçük Dil Modelleri (SLM) ile Özetlenmesi  
**Hazırlayan:** Emrah Aksu (258273001032)  
**Tarih:** 29 Mayıs 2026
"""

import re
import pandas as pd
from datasets import load_dataset

def advanced_legal_extraction_pipeline(text):
    """
    Dersimizin öğretim üyesi rehberliğinde geliştirilen Regex Extraction Pipeline.
    Metindeki kurumsal gürültüleri temizler ve gerçek Özet/İçtihat/Gerekçe bölümlerini ayıklıyoruz.
    """
    # Hata veren satır düzeltildi: len(text.strip()) yapıldı.
    if not isinstance(text, str) or len(text.strip()) == 0:
        return None, None

    # 1. Genel Kurumsal Gürültülerin Temizlenmesi (Vize kodunun geliştirilmiş hali)
    clean_text = re.sub(r'T\.C\.\s*(YARGITAY|DANIŞTAY)?\s*\d*\s*\.?\s*(HUKUK|CEZA)?\s*(DAİRESİ|GENEL KURULU)?', '', text, flags=re.IGNORECASE)
    clean_text = re.sub(r'(ESAS|KARAR)\s*NO\s*:\s*\d+/\d+', '', clean_text, flags=re.IGNORECASE)
    clean_text = re.sub(r'\s+', ' ', clean_text).strip()

    # 2. Gerçek Özet, İçtihat veya Gerekçe Bölümlerinin Dinamik Ayıklanması
    patterns = [
        r'(ÖZET\s*:\s*.*?)(?=İÇTİHAT\s*:|KARAR\s*:|GEREKÇE\s*:|$)',
        r'(İÇTİHAT\s*:\s*.*?)(?=KARAR\s*:|GEREKÇE\s*:|$)',
        r'(GEREKÇE\s*:\s*.*?)(?=KARAR\s*:|$)'
    ]

    extracted_summary = ""
    for pattern in patterns:
        match = re.search(pattern, clean_text, flags=re.IGNORECASE | re.DOTALL)
        if match:
            extracted_summary = match.group(1).strip()
            break

    # Eğer metinde spesifik bir özet başlığı yoksa, metnin ilk %20'sini özet (hedef),
    # kalan %80'ini ise temizlenmiş tam metin (girdi) kabul ediyoruz.
    if not extracted_summary and len(clean_text) > 200:
        split_point = int(len(clean_text) * 0.2)
        extracted_summary = clean_text[:split_point].strip() + "..."
        clean_text = clean_text[split_point:].strip()

    return clean_text, extracted_summary

def prepare_dataset_for_sml():
    print(">>> Adım 1: Başarıyla erişilebilen veri seti yükleniyor...")
    try:
        dataset = load_dataset("Turkish-NLI/legal_nli_TR_V1", split='train')
        df = pd.DataFrame(dataset)
        print(f" Başarılı! Toplam ham kayıt sayısı: {len(df)}")
    except Exception as e:
        print(f" Veri seti yüklenirken hata oluştu: {e}")
        return None

    text_column = 'premise' if 'premise' in df.columns else df.columns[0]

    print("\n>>> Adım 2: Gelişmiş Extraction Pipeline çalıştırılıyor (Özet/İçtihat ayıklanıyor)...")
    cleaned_documents = []
    extracted_summaries = []

    # Hızlı test ve RTX 3050 optimizasyonu için ilk 50.000 kayıt işleniyor
    sample_df = df.head(50000).copy()

    for idx, row in sample_df.iterrows():
        raw_text = row[text_column]
        doc, summary = advanced_legal_extraction_pipeline(raw_text)
        cleaned_documents.append(doc)
        extracted_summaries.append(summary)

    sample_df['cleaned_text'] = cleaned_documents
    sample_df['target_summary'] = extracted_summaries

    # 3. Hocanın İstediği Token Uzunluk Filtresi (1500 - 3000 Token aralığı kıyası)
    print("\n>>> Adım 3: Uzunluk filtrelemesi uygulanıyor (1500 - 3000 Token arası)...")
    sample_df['token_count_est'] = sample_df['cleaned_text'].apply(lambda x: len(str(x).split()) if x else 0)

    # 1100 kelime ile 2300 kelime arası (Ortalama 1500-3000 token standardı)
    filtered_df = sample_df[(sample_df['token_count_est'] >= 1100) & (sample_df['token_count_est'] <= 2300)].copy()

    filtered_df = filtered_df.dropna(subset=['cleaned_text', 'target_summary'])
    filtered_df = filtered_df[filtered_df['target_summary'].str.strip() != ""]

    print(f" Filtreleme Sonrası Kalan Yüksek Kaliteli Kayıt Sayısı: {len(filtered_df)}")

    filtered_df[['cleaned_text', 'target_summary']].to_csv("final_processed_legal_data.csv", index=False)
    print(" Veri 'final_processed_legal_data.csv' adıyla Colab diskine kaydedildi.")

    return filtered_df

if __name__ == "__main__":
    processed_df = prepare_dataset_for_sml()
    if processed_df is not None and len(processed_df) > 0:
        print("\n İşlem Kusursuz Tamamlandı! Örnek çıktıları inceleyebilirsin:")
        print("-" * 50)
        print(f"GİRDİ (Temizlenmiş Metin - İlk 200 karakter):\n{processed_df['cleaned_text'].iloc[0][:200]}...")
        print("-" * 50)
        print(f"HEDEF ÖZET (Ayıklanan Kısım - İlk 200 karakter):\n{processed_df['target_summary'].iloc[0][:200]}...")
        print("-" * 50)
